# Generated by Django 4.1.11 on 2023-09-10 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 14, 21, 13, 545694)),
        ),
    ]
