# Generated by Django 4.1.11 on 2023-09-17 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_song_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 23, 8, 41, 132828, tzinfo=datetime.timezone.utc)),
        ),
    ]
