# Generated by Django 4.1.11 on 2023-09-17 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_song_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
