# Generated by Django 4.1.11 on 2023-09-19 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_song_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_art',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='sound_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'flac', 'aiff', 'alac', 'ogg'])]),
        ),
    ]
