# Generated by Django 4.1.11 on 2023-09-19 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_song_song_art_alter_song_sound_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sound_file',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'flac', 'aiff', 'alac', 'ogg'])]),
        ),
    ]
