# Generated by Django 4.1.11 on 2023-09-21 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_song_options_alter_song_song_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_art',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
